global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - "prometheus:9090"
          - "s3-master:9324"
          - "s3-volume:9325"
          - "s3-filer:9326"
          - "s3:9327"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "rules.yml"
