version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:  
  prometheus:
      image: prom/prometheus
      restart: on-failure
      ports:
        - 9000:9090
      volumes:
        - ./conf:/etc/prometheus
      command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
      networks:
        - stamford

  alertmanager:
    image: prom/alertmanager
    restart: on-failure
    volumes:
      - ./conf/alertmanager.yml:/etc/prometheus/alertmanager.yml
    command: --config.file=/etc/prometheus/alertmanager.yml
    ports:
      - 9093:9093
    networks:
      - stamford

  discord-alert:
    image: benjojo/alertmanager-discord
    restart: on-failure
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK_URL}
    networks:
        - stamford