version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford
  monitoring:

services:  
  prometheus:
      image: prom/prometheus
      restart: on-failure
      ports:
        - 9000:9090
      volumes:
        - ./conf:/etc/prometheus
      command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
      networks:
        - stamford
        - monitoring

  node-exporter:
    image: prom/node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager
    restart: on-failure
    volumes:
      - ./conf/alertmanager.yml:/etc/prometheus/alertmanager.yml
    command: --config.file=/etc/prometheus/alertmanager.yml
    ports:
      - 9093:9093
    networks:
      - monitoring

  discord-alert:
    image: benjojo/alertmanager-discord
    restart: on-failure
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK_URL}
    networks:
        - monitoring