version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  prometheus:
    image: prom/prometheus
    restart: on-failure
    ports:
      - 9000:9090
    volumes:
      - ./conf:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - stamford

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./conf/grafana/provisioning:/etc/grafana/provisioning 
      - ./conf/grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - stamford

  alertmanager:
    image: prom/alertmanager
    restart: on-failure
    volumes:
      - ./conf/alertmanager.yml:/etc/prometheus/alertmanager.yml
    command: --config.file=/etc/prometheus/alertmanager.yml
    ports:
      - 9093:9093
    depends_on:
      - prometheus
    networks:
      - stamford

  discord-alert:
    image: benjojo/alertmanager-discord
    restart: on-failure
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK_URL}
    depends_on:
      - prometheus
    networks:
      - stamford
