version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:  
  onboarding:
    image: ghcr.io/stamford-syntax-club/onboarding-basics:52097960875d480ebef1a8b111221f3af221a06a
    restart: on-failure
    expose:
      - 80
    networks:
      - stamford

