version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:  
  onboarding:
    image: ghcr.io/stamford-syntax-club/onboarding-basics:e161965d3aa57b2ec1b5e06fa007de3ef7e883e3
    restart: on-failure
    expose:
      - 80
    networks:
      - stamford

