version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:  
  onboarding:
    image: ghcr.io/stamford-syntax-club/onboarding-basics:f6db3a2b4a87076f31d969b3c915d1ddc743615e
    restart: on-failure
    expose:
      - 80
    networks:
      - stamford

