version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:  
  onboarding:
    image: ghcr.io/stamford-syntax-club/onboarding-basics:66b6ffd022a397f47ce0c38adcd0c8bbc9910301
    restart: on-failure
    expose:
      - 80
    networks:
      - stamford

