version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:  
  onboarding:
    image: ghcr.io/stamford-syntax-club/onboarding-basics:ee549f68c9f9699ac6b17dc14eea29693f9d6c83
    restart: on-failure
    expose:
      - 80
    networks:
      - stamford

