version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:  
  onboarding:
    image: ghcr.io/stamford-syntax-club/onboarding-basics:3dd45f57f32228e090660b709c83cbd1c1ecab55
    restart: on-failure
    expose:
      - 80
    networks:
      - stamford

