version: "3.8"

networks:
  stamford:

services:
  haproxy:
    image: haproxy
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./haproxy.prod.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - stamford
