version: "3.8"

networks:
  stamford:

services:
  haproxy:
    image: haproxy
    container_name: haproxy
    restart: always
    ports:
      - 443:443
      - 80:80
      - 8404:8404
    volumes:
      - ./haproxy.beta.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - stamford
