version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  s3-master:
    image: chrislusf/seaweedfs
    restart: on-failure
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=s3-master -ip.bind=0.0.0.0  -volumeSizeLimitMB=5 -volumePreallocate=false -mdir=/data"
    volumes:
      - ./data/master:/data
    networks:
      - stamford

  s3-volume:
    image: chrislusf/seaweedfs
    restart: on-failure
    ports:
      - 8181:8181
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="s3-master:9333" -ip.bind=0.0.0.0 -port=8181 -max=0 -metricsPort=9325 -dir=/data'
    depends_on:
      - s3-master
    volumes:
      - ./data/volume:/data
    networks:
      - stamford

  s3-filer:
    image: chrislusf/seaweedfs
    restart: on-failure
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master="s3-master:9333" -ip.bind=0.0.0.0 -defaultStoreDir=/data'
    tty: true
    stdin_open: true
    depends_on:
      - s3-master
      - s3-volume
    volumes:
      - ./data/filer:/data
    networks:
      - stamford

  s3:
    image: chrislusf/seaweedfs
    restart: on-failure
    ports:
      - 8333:8333
    command: 's3 -config=/conf/config.json -filer="s3-filer:8888" -ip.bind=0.0.0.0'
    volumes:
      - ./config.json:/conf/config.json
    depends_on:
      - s3-master
      - s3-volume
      - s3-filer
    networks:
      - stamford
