version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: on-failure
    ports:
      - 1342:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    networks:
      - stamford
