version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  frontend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-frontend:68a487adcb05da2e27e694210ecf264c8c538874
    restart: always
    networks:
      - stamford
      
  backend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-backend:5f93e025fd7f8ff47fe21df8a3a9a19f4e72955f
    networks:
      - stamford
    ports:
      - 8080:${PORT}
    environment:
      - PORT=${PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGODB_URI=${MONGODB_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
