version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  frontend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-frontend:c3e3b3dd54fe07fee6857f51181ba3eb17498159
    restart: always
    networks:
      - stamford
    environment:
      - APP_ENV=production

  backend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-backend:f619ad1f272f9bf8f04936d15a55dcc0c66f1fd3
    networks:
      - stamford
    ports:
      - 8080:${PORT}
    environment:
      - PORT=${PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGODB_URI=${MONGODB_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - APP_ENV=production
