version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  # frontend
  frontend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-frontend:e6420ffb88d4c170af0ae691079f37be3b7b7e0c
    restart: always
    networks:
      - stamford
      
  # backend
