version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  frontend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-frontend:a0edeb6835ccb98ab447584e1579050611d58b84
    restart: always
    networks:
      - stamford
      
  backend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-backend:7b095a854deb8915a53956aa01bcf6896a14c591
    networks:
      - stamford
    ports:
      - 8080:${PORT}
    environment:
      - PORT=${PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGODB_URI=${MONGODB_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
