version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford
  redis_internal:
    external: true
    name: redis_internal

services:
  frontend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-frontend:b496e7830c0acb0aa8d55d98773268d532f649e3
    container_name: center-fe
    restart: always
    networks:
      - stamford
    environment:
      - APP_ENV=production

  backend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-backend:f619ad1f272f9bf8f04936d15a55dcc0c66f1fd3
    container_name: center-be
    restart: always
    networks:
      - stamford
      - redis_internal
    ports:
      - 8080:${PORT}
    environment:
      - PORT=${PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - APP_ENV=production
