version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  frontend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-frontend:0e47a9f7c629c1282b4cfba41389ed0c997f74ad
    restart: always
    networks:
      - stamford
    environment:
      - APP_ENV=beta

  backend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-backend:e9c926b00636faa0b7f90833a26832e5a63d70b6
    networks:
      - stamford
    ports:
      - 8080:${PORT}
    environment:
      - PORT=${PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGODB_URI=${MONGODB_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - APP_ENV=beta
