version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  # frontend
  frontend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-frontend:68a487adcb05da2e27e694210ecf264c8c538874
    restart: always
    networks:
      - stamford
      
  # backend
