version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  frontend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-frontend:4a0907c6a444a0d46e63e394c531b0439bb3185a
    restart: always
    networks:
      - stamford
    environment:
      - APP_ENV=beta

  backend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-backend:cd9e4602ce722561ea87e8d150acf452a6f1aa08
    networks:
      - stamford
    ports:
      - 8080:${PORT}
    environment:
      - PORT=${PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGODB_URI=${MONGODB_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - APP_ENV=beta
