version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  frontend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-frontend:4963619382ff50604914d61b784bba3742cc40c2
    restart: always
    networks:
      - stamford
    environment:
      - APP_ENV=beta

  backend:
    image: ghcr.io/stamford-syntax-club/stamfordcenter-backend:e5d17db8a53073c78dc79c7d5617cd161a754b34
    networks:
      - stamford
    ports:
      - 8080:${PORT}
    environment:
      - PORT=${PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGODB_URI=${MONGODB_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - APP_ENV=beta
