version: "3.8"
networks:
  stamford:

services:
  redis:
    image: redis
    restart: on-failure
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - stamford
