name: Deploy to VM

on:
  push:
    branches:
      - "main"

jobs:
  deploy-to-vm:
    name: Deploy new changes to VM
    runs-on: ubuntu-latest
    steps:
      - name: Deploy new changes via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd infra
            git fetch origin
            git pull origin main
            ./start_dev.sh
