name: Dev Deployment

# Run this pipeline to create PR whenever branch deploy/<...>  is pushed
on:
  push:
    branches:
      - "deploy/**"

jobs:
  pr:
    name: Open Pull Request
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: |
          curl https://api.github.com/repos/stamford-syntax-club/infra/pulls \
            --header "Authorization: token ${{ secrets.WORKFLOW_TOKEN }}" \
            -X POST \
            -H "Content-Type:application/json" \
            -d '{ "title": "Title of my PR", "body": "Automated PR to ...", "head": "${{ github.head_ref }}", "base": "main" }'
