name: Dev Deployment

# Run this pipeline to create PR whenever branch deploy/<...>  is pushed
on:
  push:
    branches:
      - "deploy/**"

jobs:
  pr:
    name: Open Pull Request
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ github.ref_name }}
          base: main
          title: test create pr with pipeline
          body: pr with pipeline
