name: Dev Deployment

# Run this pipeline to create PR whenever branch deploy/<...>  is pushed
on:
  push:
    branches:
      - "deploy/**"

jobs:
  pr:
    name: Open Pull Request
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.head.ref }}
          target_branch: main
