name: Dev Deployment

# Run this pipeline to create PR whenever branch deploy/<...>  is pushed
on:
  push:
    branches:
      - "deploy/**"

env:
  BRANCH_NAME: ${{ github.head_ref }}

jobs:
  pr:
    name: Open Pull Request
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: |
          PAYLOAD=$(cat <<EOF
            {
              "title": "Title of my PR",
              "body": "Automated PR to ...",
              "head": "${BRANCH_NAME}",
              "base": "main"
            }
          EOF
          )
          curl https://api.github.com/repos/stamford-syntax-club/infra/pulls \
            --header "Authorization: token ${ TOKEN }" \
            -H "Content-Type:application/json" \
            -d "$PAYLOAD"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
